### ISSUE TITLE
libvirt-fix-cpu-driver.ps1 is missing

### ISSUE THREAD

**Issue by kmpm** [rgl/windows-2016-vagrant#4]
Hi, just tried to use your script but `libvirt-fix-cpu-driver.ps1` seems to be missing from the repo.

packer tries to use the file when running `packer build -only=windows-2016-amd64-virtualbox .\windows-2016.json` on a Windows 10 machine from a powershell prompt.

**Comment by rgl** [comment]
I've removed that reference in https://github.com/rgl/windows-2016-vagrant/commit/06f83e051ee28818051684843168e4b7e8e5354d. Thx for the heads up!
